GET /api/gestel/facturas
Host: {{host}}

###
#
###
GET /api/gestel/facturas/1
Host: {{host}}

###
#
###
GET /api/gestel/facturas/1/get
Host: {{host}}

{
  "csv": "1010000000244.csv"
}

###
# TEsts
###
GET /api/gestel/facturas/1/test
Host: {{host}}

{
  "csv": "10100000091.csv"
}
###
#
###
POST /api/gestel/facturas
Host: {{host}}

###
# Get Tels
###
GET /api/gestel/facturas/etecsa
Host: {{host}}

{
  "mes": 1,
  "year":2022
}