
#############################
### Gestel Facturas
#############################

###
# List
###
GET /api/gestel/facturas
Host: {{host}}

###
# Seed
###
GET /api/gestel/facturas/seed
Host: {{host}}

###
# Get Tels
###
GET /api/gestel/facturas/etecsa
Host: {{host}}

{
  "mes": 1,
  "year":2022
}