#############################
### Gestel Telefonos
#############################

###
# Create
###
POST /api/gestel/tels
Host: {{host}}
Authorization: {{token}}

{
  "servicio":"AUTOMATICO",
  "tipo":"PRIVADO",
  "presupuesto":28000,
  "cargo_id":1,
  "telf": "557812",
  "comentario":"comment"
}

###
# Get
###
GET /api/gestel/tels/1
Host: {{host}}

###
# List
###
GET /api/gestel/tels
Host: {{host}}

###
# Pasados
###
GET /api/gestel/tels/pasados
Host: {{host}}
Authorization: {{token}}

{
  "mes":1,
  "year":2022
}

###
# Remove
###
DELETE  /api/gestel/tels/1
Host: {{host}}
Authorization: {{token}}

###
# Search
###
GET /api/gestel/tels/search
Host: {{host}}

{
  "search": "43",
  "type": "tel"
}

###
# Update
###
PUT /api/gestel/tels/1
Host: {{host}}
Authorization: {{token}}

{
  "servicio":"AUTOMATICO",
  "tipo":"PRIVADO,PUBLICO",
  "presupuesto":28000,
  "cargo_id":1
}